[package]
name = "ansi2tex"
version = "0.1.0"
edition = "2021"
authors = ["RubixDev", "MikMuellerDev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.22", features = ["derive"] }
